# Generated by Django 5.2.11 on 2026-02-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpverification_user_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='role',
            field=models.CharField(default='Customer', max_length=20),
        ),
    ]
