# Generated by Django 5.2.11 on 2026-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_admin_note_event_reviewed_at_event_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
