# Generated by Django 5.2.11 on 2026-03-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_screen_gold_count_screen_gold_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
