# Generated by Django 5.2.11 on 2026-02-20 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='theaters.seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.show'),
        ),
    ]
