# Generated by Django 5.2.11 on 2026-03-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
