# Generated by Django 5.2.11 on 2026-02-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('language', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('status', models.CharField(choices=[('Now Showing', 'Now Showing'), ('Coming Soon', 'Coming Soon')], default='Now Showing', max_length=20)),
            ],
        ),
    ]
